apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/easy-llm-benchmarker

patches:
  - path: easy-llm-benchmarker/patches.yaml

images:
  - name: ghcr.io/highsoft-corp/easy-llm-benchmarker-web
    newTag: 0.1.0
  - name: ghcr.io/highsoft-corp/easy-llm-benchmarker-api
    newTag: 0.1.0
  - name: ghcr.io/highsoft-corp/easy-llm-benchmarker-worker
    newTag: 0.1.0
