apiVersion: v1
kind: Service
metadata:
  name: easy-llm-benchmarker-api
spec:
  selector:
    app.kubernetes.io/name: easy-llm-benchmarker-api
    app.kubernetes.io/part-of: easy-llm-benchmarker
  ports:
    - name: http
      port: 8787
      targetPort: http
